/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallan.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LastMonthSummary {

	@JsonProperty("previousMonthCollection")
	private String previousMonthCollection = "0";

	@JsonProperty("previousMonthNewExpense")
	private String previousMonthNewExpense = "0";

	@JsonProperty("cumulativePendingExpense")
	private String cumulativePendingExpense = "0";
	
	@JsonProperty("previousMonthYear")
	private String previousMonthYear ="";

}
