/// Flutter icons HomeIconsModified
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIconsModified
///      fonts:
///       - asset: fonts/HomeIconsModified.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIconsModified {
  HomeIconsModified._();

  static const _kFontFam = 'HomeIconsModified';
  static const String? _kFontPkg = null;

  static const IconData vector_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
