/// Flutter icons HomeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcons
///      fonts:
///       - asset: fonts/HomeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIcons {
  HomeIcons._();

  static const _kFontFam = 'HomeIcons';
  static const String? _kFontPkg = null;

  static const IconData addexpenses = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collectpayment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData createconsumer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generaedemand = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hhregister = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printreciept = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData updateconsumer = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData updateexpenses = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gpwscdetails = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
