// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvWEo6L8z1uwHTxRQFhqGNrMLY-Zl5uk',
    appId: '1:692739843757:web:b948b0f792046fbc5f4824',
    messagingSenderId: '692739843757',
    projectId: 'naljalseva-prod-434bd',
    authDomain: 'naljalseva-prod-434bd.firebaseapp.com',
    storageBucket: 'naljalseva-prod-434bd.appspot.com',
    measurementId: 'G-KCLZBTMBK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hOeHQnWqCnW82Y5kKr8RvaioxdlsFSk',
    appId: '1:692739843757:android:6fc4c4a8d205216e5f4824',
    messagingSenderId: '692739843757',
    projectId: 'naljalseva-prod-434bd',
    storageBucket: 'naljalseva-prod-434bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4x3aTKFsr07Gc-0Xt6FJRPVJtjfiAMVU',
    appId: '1:692739843757:ios:b98a0983b37edbec5f4824',
    messagingSenderId: '692739843757',
    projectId: 'naljalseva-prod-434bd',
    storageBucket: 'naljalseva-prod-434bd.appspot.com',
    iosBundleId: 'com.jjm.naljalseva',
  );

}