CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_id ON egbs_bill_v1 USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_isactive ON egbs_bill_v1 USING btree (isactive);
CREATE INDEX IF NOT EXISTS  idx_egbs_bill_v1_tenantid ON egbs_bill_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_bill_v1 ON egbs_bill_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_billaccountdetails_v1 ON egbs_billaccountdetail_v1 USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_businessservice ON egbs_billdetail_v1 USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_consumercode ON egbs_billdetail_v1 USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_billdetail_v1_tenantid ON egbs_billdetail_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_billdetail_v1 ON egbs_billdetail_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_biz_srvc_det ON egbs_business_service_details USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  unq_businessservice ON egbs_business_service_details USING btree (businessservice, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_collectedreceipts ON egbs_collectedreceipts USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_businessservice ON egbs_demand_v1 USING btree (businessservice);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_consumercode ON egbs_demand_v1 USING btree (consumercode);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_consumertype ON egbs_demand_v1 USING btree (consumertype);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_id ON egbs_demand_v1 USING btree (id);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_payer ON egbs_demand_v1 USING btree (payer);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_taxperiodfrom ON egbs_demand_v1 USING btree (taxperiodfrom);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_taxperiodto ON egbs_demand_v1 USING btree (taxperiodto);
CREATE INDEX IF NOT EXISTS  idx_egbs_demand_v1_tenantid ON egbs_demand_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demand_v1 ON egbs_demand_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  uk_egbs_demand_v1_consumercode_businessservice ON egbs_demand_v1 USING btree (consumercode, tenantid, taxperiodfrom, taxperiodto, businessservice);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demand_v1_audit ON egbs_demand_v1_audit USING btree (id, tenantid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demanddetail_v1_demandid ON egbs_demanddetail_v1 USING btree (demandid);
CREATE INDEX IF NOT EXISTS  idx_egbs_demanddetail_v1_tenantid ON egbs_demanddetail_v1 USING btree (tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demanddetail_v1 ON egbs_demanddetail_v1 USING btree (id, tenantid);
CREATE UNIQUE INDEX IF NOT EXISTS  pk_egbs_demanddetail_v1_audit ON egbs_demanddetail_v1_audit USING btree (id, tenantid);
